// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACykl4m8C7NUTXfoyQ7PQve-3Zqjxqeoc',
    appId: '1:734098285346:web:6c0d95b707cf6b408c7b7b',
    messagingSenderId: '734098285346',
    projectId: 'strefa-ciszy',
    authDomain: 'strefa-ciszy.firebaseapp.com',
    storageBucket: 'strefa-ciszy.firebasestorage.app',
    measurementId: 'G-VM6X22GFD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkXiS4JP9iySRXxzOiI1oN0_EmI6Tx208',
    appId: '1:734098285346:android:35076c831ae883eb8c7b7b',
    messagingSenderId: '734098285346',
    projectId: 'strefa-ciszy',
    storageBucket: 'strefa-ciszy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5XWb0W5mm-9dEJk0x6SNoebE1z6zE2w4',
    appId: '1:734098285346:ios:70263400213519028c7b7b',
    messagingSenderId: '734098285346',
    projectId: 'strefa-ciszy',
    storageBucket: 'strefa-ciszy.firebasestorage.app',
    iosBundleId: 'com.ash.strefaciszy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5XWb0W5mm-9dEJk0x6SNoebE1z6zE2w4',
    appId: '1:734098285346:ios:f59d270ad2fa4e588c7b7b',
    messagingSenderId: '734098285346',
    projectId: 'strefa-ciszy',
    storageBucket: 'strefa-ciszy.firebasestorage.app',
    iosBundleId: 'com.example.strefaCiszy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACykl4m8C7NUTXfoyQ7PQve-3Zqjxqeoc',
    appId: '1:734098285346:web:9a3276fecdea0dbf8c7b7b',
    messagingSenderId: '734098285346',
    projectId: 'strefa-ciszy',
    authDomain: 'strefa-ciszy.firebaseapp.com',
    storageBucket: 'strefa-ciszy.firebasestorage.app',
    measurementId: 'G-1363641X0R',
  );
}
